var songsArray = [];
console.log(songsArray);

function Song (name, answer1, answer2, answer3, answer4, answer5, answer6, answer7) {
  this.name = name;
  this.question1 = answer1;
  this.question2 = answer2;
  this.question3 = answer3;
  this.question4 = answer4;
  this.question5 = answer5;
  this.question6 = answer6;
  this.question7 = answer7;
  this.compatibility = 0;
  songsArray.push(this);
};

var newYork = new Song('Welcome to New York', 'Cumulus', 'Pink', 'Jake Gyllenhaal');
var blankSpace = new Song('Blank Space', 'Stratus', 'Purple', 'Zac Efron' );
var style = new Song('Style', 'Stratocumulus', 'Red', 'Taylor Lautner');
var woods = new Song('Out of the Woods', 'Stratus', 'Blue' );
var stay = new Song('All You Had to Do Was Stay', 'Cumulonimbus', 'Purple', 'Taylor Lautner');
var blankSpace = new Song('Blank Space', 'Stratus', 'Purple', 'Zac Efron' );
var shake = new Song('Shake It Off', 'Stratus', 'Red', 'Taylor Lautner');
var wish = new Song('I Wish You Would', 'Cumulonimbus', 'Blue', 'Zac Efron');
var blood = new Song('Bad Blood', 'Cumulus', 'Red', 'Jake Gyllenhaal');
var dreams = new Song('Wildest Dreams', 'Stratus', 'Blue');
var girl = new Song('How you Get the Girl', 'Stratus', 'Pink', 'Jake Gyllenhaal');
var love = new Song('This Love', 'Cumulonimbus', 'Blue', 'Taylor Lautner' );
var places = new Song('I Know Places', 'Cumulus, Purple', 'Taylor Lautner');
var clean = new Song('Clean', 'Cumulus', 'Red', 'Jake Gyllenhaal');
var grace = new Song('State of Grace', 'Cumulonimbus', 'Pink');
var red = new Song('Red', 'Cumulus', 'Blue');
var treacherous = new Song('Treacherous', 'Stratus', 'Red');
var trouble = new Song('I Knew You Were Trouble', 'Stratocumulus', 'Purple' );
var well = new Song( 'All Too Well', 'Cumulonimbus', 'Pink', 'Jake Gyllenhaal');
var twentyTwo = new Song('22', 'Cumulonimbus', 'Red' );
var almost = new Song("Almost Do", 'Cumulus', 'Pink', 'Taylor Lautner');
var ever = new Song('We Are Never Getting Back Together', 'Stratocumulus', 'Purple', 'Taylor Lautner');
var stay = new Song('Stay Stay Stay', 'Stratus', 'Pink');
var time = new Song('The Last Time', 'Stratus', 'Red' );
var holy = new Song('Holy Ground', 'Cumulus', 'Purple'  );
var beautiful = new Song('Sad Beautiful Tragic', 'Stratocumulus', 'Blue', 'Pink' );
var lucky = new Song('The Lucky One', 'Stratus', 'Blue', 'Jake Gyllenhaal');
var changed = new Song('Everything Has Changed', 'Stratocumulus', 'Pink', 'Taylor Lautner');
var starlight = new Song('Starlight', 'Stratus', 'Purple');
var again = new Song('Begin Again', 'Cumulus', 'Red', 'Taylor Lautner');
var story = new Song('Love Story', 'Stratus, Purple', 'Jake Gyllenhaal'  );
